### PR TITLE
Merge with falkcarl fork (grmp and gpcmp models)

### PR DESCRIPTION
**Pull request by falkcarl**
Major differences consist of the addition of grmp and gpcmp item models and documentation, minor tweaks to lmp. gpcmp still needs dTheta or a workaround.

### CODE REVIEW

**Comment by jpritikin** [comment]
Nice! I'll probably merge it before 2020.

**Comment by falkcarl** [comment]
Oops, looks like I need to fix one more test. Glad we have tests.

**Comment by falkcarl** [comment]
Travis CI check now passes. Is codecov just telling us that we don't yet have checks in place that actually test much of the new gpcmp and grmp code?

**Comment by jpritikin** [comment]
> Is codecov just telling us that we don't yet have checks in place that actually test much of the new gpcmp and grmp code?

Yeah, don't worry about that. I had time to get coverage reporting set up, but haven't worked to increase coverage yet.

**Pull request merged**
